### ISSUE TITLE
plugin creation in gridelements container fails

### ISSUE THREAD

**Issue by EnzephaloN** [PHORAX/formhandler#1]
TYPO3 7.6.15 +gridelements 7.0.6-dev + bootstrap_grids 1.3.1 + formhandler 2.4.0

Create a grid-CE on a page.
Create a formhandler-plugin inside a column of that grid-CE.
The formhandler-plugin is not there because fields tx_gridelements_columns and tx_gridelements_container set to 0.  
Any other CE works, but not formhandler-plugin.

Creation of formhandler-plugins outside a grid-CE works, also moving that plugin into grid-CE. Only creation inside grid-CE fails.

**Comment by EnzephaloN** [comment]
Johannes C. Schulz [9:23 AM] 
Okay, some investigation later:
It's about ext_tables.php and the creation of the tt_content type. After changing the TCA to (see last row)
```
$TCA['tt_content']['types'][$_EXTKEY . '_pi1']['showitem'] = '
        --palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.general;general,
        --palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.header;header,
        --div--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.plugin,pi_flexform,
        --div--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.access,
        --palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.visibility;visibility,
        --palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.access;access,
        --div--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.appearance,
        --palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.frames;frames,
        --div--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.behaviour,
        --div--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.extended,
        --div--;LLL:EXT:gridelements/Resources/Private/Language/locallang_db.xlf:gridElements,tx_gridelements_container,tx_gridelements_columns
    ';
```
it works.
But thats a bloody hack. Anyone an idea how to do this correctly?

**Comment by EnzephaloN** [comment]
Inside my theme-extension I do this:

ext_tables.php:
``` 
if (TYPO3_MODE === 'BE' && TYPO3\CMS\Core\Utility\ExtensionManagementUtility::isLoaded('formhandler') && TYPO3\CMS\Core\Utility\ExtensionManagementUtility::isLoaded('gridelements')) {
    $append_2_tca = ",
		--div--;LLL:EXT:gridelements/Resources/Private/Language/locallang_db.xlf:gridElements,tx_gridelements_container,tx_gridelements_columns";
    $TCA['tt_content']['types']['formhandler_pi1']['showitem'] .= $append_2_tca;
}
```

**Comment by SvenJuergens** [comment]
@EnzephaloN hi, is it still a problem?
i can't reproduce the described behavior.
my config is TYPO3 7.6.16 + current git version gridelements branch 7-0, + bootstrap_grids 1.3.1 + formhandler 2.4.0

**Comment by EnzephaloN** [comment]
Hello
With the last version of gridelements Jo Hasenau changed the TCA-enhancing. So now it's fixes.
