### ISSUE TITLE
Call to undefined method TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::getPageRenderer()

### ISSUE THREAD

**Issue by codewtal** [PHORAX/formhandler#10]
I replaced
$pageRenderer = $GLOBALS['TSFE']->getPageRenderer();
by 
$pageRenderer = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Core\Page\PageRenderer::class);
in /formhandler/Classes/Controller/Form.php
to solve this issue.

**Comment by 7elix** [comment]
Solved in the meantime.
