### ISSUE TITLE
No Output in Formsite Frontend on 8.7.8

### ISSUE THREAD

**Issue by ProWebs** [PHORAX/formhandler#16]
I installed you extension but i only got a empty div on the formsite.
Also by activated debugs without any error outbut
`plugin.Tx_Formhandler.settings.predef.validation-contact {

    debug = 1 
    addErrorAnchors = 1  

    name = Kontakt Formular`

I copyed a old TS from a working typo web (7.6.x), so the TS code should be fine.
There is no output and also no error in any logfile.
Any suggestions to this issue?

**Comment by 7elix** [comment]
Hi @ProWebs ,

there is no general issue concerning output.
Please send further details - including complete TS and check settings in tt_content element.

**Comment by 7elix** [comment]
Close due to missing feedback
