### ISSUE TITLE
filter formhandler log throws an error

### ISSUE THREAD

**Issue by tayfur79** [PHORAX/formhandler#32]
When i use the filter in the forhandler log and set an startdate i get following error:

> An error occurred while trying to call Typoheads\Formhandler\Controller\ModuleController->indexAction()

I tried formhandler 2.4.1 and also 3.1.0 but same problem appears. I am using TYPO3 8.7.20

**Comment by tayfur79** [comment]
![2018-12-06_06h16_40](https://user-images.githubusercontent.com/38519750/49563089-8a559600-f91e-11e8-8d5e-a711c1e8d88f.png)

**Comment by SvenJuergens** [comment]
hi @tayfur79 
I'm not sure, but try this one out [[BUGFIX] make Backend Module Search with start and end Date work again](https://github.com/SvenJuergens/formhandler/commit/fac96ff17ec996e6d87bd28769d36d50a886cbb3)

**Comment by tayfur79** [comment]
many thanks, this solved my problem
