### ISSUE TITLE
double encoding in TYPO 9.5

### ISSUE THREAD

**Issue by SvenJuergens** [PHORAX/formhandler#35]
hi @7elix 

if you have a normal form on a site and use some special character in the fields like & or ", this got encoded twice. "&" --> $amp;amp;
it's related to this change: https://github.com/PHORAX/formhandler/commit/5a1e223d7d6d3af419bdbb5e2cebaeecc468978f

with TYPO3 8 all things went fine, but in 9.5 you have the double encoding. 
do you have an idea where that comes from and how to fix it?

best regards
Sven

**Comment by Schweriner** [comment]
@SvenJuergens Just for interest: Are you processing your Form Template through FLUIDTEMPLATE?

**Comment by SvenJuergens** [comment]
@Schweriner thanks for your Feedback.
he formhandler templates are not FlUIDTEMPLATES based.
(did not even know that this is possible)

**Comment by 7elix** [comment]
Hi @SvenJuergens 

this issue is closed due to inactivity and missing PR. Feel free to open another issue, preferably with a corresponding pull request. 

Thank you 🙏
