### ISSUE TITLE
TYPO3 9.x: $GLOBALS['TSFE']->renderCharset not available anymore

### ISSUE THREAD

**Issue by Caprico85** [PHORAX/formhandler#36]
The option $GLOBALS['TSFE']->renderCharset was marked deprecated in TYPO3 8.0 (see [change #73794](https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.0/Deprecation-73794-SearchFormController-utf8_to_currentCharsetAndTSFE-renderCharset.html)) and completely removed in TYPO3 9.0 (see [change #80700](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Breaking-80700-DeprecatedFunctionalityRemoved.html)).

renderCharset is still used in some validators, for example Classes/Validator/ErrorCheck/MaxLength.php.

**Comment by 7elix** [comment]
Could you send a merge request removing the renderCharset checks?

**Comment by SvenJuergens** [comment]
@7elix maybe you can cherry-pick  this https://github.com/SvenJuergens/formhandler/commit/ee4b834df728a7bfdb622831a95828a4df033092

**Comment by 7elix** [comment]
Solved by 85a02f4ac73d3ac30274c9a23dfafa4fe0fb6114
