### ISSUE TITLE
Compatibility LTS9

### ISSUE THREAD

**Issue by nabossha** [PHORAX/formhandler#37]
is there any official compatibility with LTS 9 planned, if yes is there a timeframe for it? thanks a lot for your feedback

**Comment by ruhland84** [comment]
official compatibility with TYPO3 9.5: +1

**Comment by SvenJuergens** [comment]
hi, this is "only" a fork of formhandler. Therefore, it is difficult to talk about "official". ;)
I also use formhandler with TYPO3 9.5 and my forms are working , but I certainly do not use all the features of formhandler. So if you can say what is not working for you then maybe it's possible to adjust that as well

**Comment by faessler** [comment]
@SvenJuergens can you upload your "working" extension somewhere?
It would be nice to examine your code.. THX

**Comment by SvenJuergens** [comment]
@faessler here is my fork https://github.com/SvenJuergens/formhandler 
The code is almost identical to the this fork one

**Comment by faessler** [comment]
@SvenJuergens 
Thank you, seems to work in backend, but I don't have any output of form in the frontend.
I took the same conf as in 6.2. Have you any ideas?

**Comment by SvenJuergens** [comment]
@faessler 
Hi, try to clean all your caches and if this is not working try first an example from here http://examples.typo3-formhandler.com/start/

If this is still not working, please open a new issue with further explanations.

**Comment by faessler** [comment]
@SvenJuergens Thanks for your answer, I'll check it as soon as I get to it.

**Comment by nabossha** [comment]
@SvenJuergens thanks for your informations. i will look into it and get back to you if there are serious problems

**Comment by luzat** [comment]
I am not sure if https://github.com/SvenJuergens/formhandler is much better than this one, but I forked it and fixed a couple of errors which occur in the backend otherwise: https://github.com/luzat/formhandler It's probably still lacking in some areas, but for the site that I am using it on all functionality seems to work.

**Comment by SvenJuergens** [comment]
@luzat hi, would you like to make a pull request?

**Comment by luzat** [comment]
@SvenJuergens On which repository? Also, most changes (not that many) are 9.5-only. Not sure if the ViewHelpers can be made to work easily with 8 and 9.

The code will get some testing on 9 during the next few days, but I could probably prepare one/some PRs towards the end of the upcoming week (and possibly clean up formatting and such, too).

**Comment by SvenJuergens** [comment]
@luzat maybe this fork an me fork? :)
would be nice, since many land here if you have something to do with formhandler. Thus one can collect the efforts around the formhandler here

**Comment by 7elix** [comment]
Hi @SvenJuergens we should decide which fork to maintain and join forces. Would you be so kind to call me sometime the next days?

**Comment by SvenJuergens** [comment]
hi @7elix If you have time look into your mailbox, I had sent you email last week. but can also reach me in typo3 slack

**Comment by 7elix** [comment]
Changes 2018 are released as 4.0.0 now.
