### ISSUE TITLE
errorCheck float

### ISSUE THREAD

**Issue by timofo** [PHORAX/formhandler#38]
If you use errorCheck **float** then you get the error: Fatal error: Cannot use 'Float' as class name as it is reserved in /html/typo3/typo3conf/ext/formhandler/Classes/Validator/ErrorCheck/Float.php on line 20

You have to rename Float.php into f.e. Phpfloat.php
Then rename the class in this file the same way.
And then you can use **phpfloat** as errorCheck.

**Comment by 7elix** [comment]
Solved by d17008947158934d8555b4cbf0f38634e876c663
