### ISSUE TITLE
confused about the Versions

### ISSUE THREAD

**Issue by cosmox** [PHORAX/formhandler#46]
In the description this is the version for TYPO3 8.7 but in the files there are customizations for TYPO3 9.5, like e.g. in ext_emconf.php

There is only one branch "Master", is there a formhandler version for TYPO3 8.7? 
I was hoping to find at least one branch for version 8 :)

**Comment by 7elix** [comment]
Hi @cosmox , the current master branch and latest release 4.0 only supports TYPO3 version 9.5^ (see https://packagist.org/packages/phorax/formhandler#4.0.0). The previous release 3.1 supports 8.7 (see https://packagist.org/packages/phorax/formhandler#3.1.0).

**Comment by cosmox** [comment]
wow this was the fastest answer ever !!!

**Comment by 7elix** [comment]
Glad to assist
