### ISSUE TITLE
notation like EXT:extensionName in TypoScript displays an error in TYPO3 v9

### ISSUE THREAD

**Issue by mym91** [PHORAX/formhandler#47]
If I use the notation EXT:extensionName/... in typoscript in TYPO3 v9, for example for the langFile, the frontend displays an error for this line: web/typo3conf/ext/formhandler/Classes/Utility/GeneralUtility.php:681 

The method extRelPath is deprecated:
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.4/Deprecation-78193-ExtensionManagementUtilityextRelPath.html

Notation like typo3conf/ext/extensionName/... is possible

**Comment by 7elix** [comment]
Solved in https://github.com/PHORAX/formhandler/commits/master
