### ISSUE TITLE
Finisher DB does not work

### ISSUE THREAD

**Issue by Schweriner** [PHORAX/formhandler#51]
For DB Inserts using the QueryBuilder we have to use ->values instead of ->set (which is for updates)

**Comment by Schweriner** [comment]
https://github.com/PHORAX/formhandler/pull/40/commits/e19e18b920e1f598e030c83ec3252051c6502337

**Comment by 7elix** [comment]
Solved by https://github.com/PHORAX/formhandler/pull/42
