### ISSUE TITLE
Caution: 2.4.1 ships an ext_emconf.php with 2.4.0

### ISSUE THREAD

**Issue by dogawaf** [PHORAX/formhandler#52]
Hi

phorax/formhandler@2.4.1 ships an ext_emconf.php with version 2.4.0

This confuses our security extension scanner.
Sadly, it is not fixable without breaking the git history.

So this issue is more a warning for users than a request for fix.

Cheers.

**Comment by b3nkai** [comment]
A patch which can be useful for those who want's the right version :)
[formhandler_extemconf_version.txt](https://github.com/PHORAX/formhandler/files/4128612/formhandler_extemconf_version.txt)

**Comment by 7elix** [comment]
Not planning to release a 2.4.2 containing correct version information in ext_emconf.
