### ISSUE TITLE
TYPO3 version 10 compatibility

### ISSUE THREAD

**Issue by 7elix** [PHORAX/formhandler#54]

**Comment by AnatoliZich** [comment]
I'm really happy to find this issue. Im trying to contribute when i have a chance

**Comment by 7elix** [comment]
Dear participants, we are looking for supports to gain TYPO3 version 10 compatibility. Please contact me in case you are interested in supporting this initiative.

**Comment by w010** [comment]
Do you ask of tweaking the classic one to work in 10, or the one being rewritten? How about progress, at what point are you? Is this usable, or is far away from finish?
For now, I have my 10-basic-compat version on my repo, it generally works in my project, but needs more work in details, like in these finishers that I never use and didn't touch at all, etc. - I made this to not have to rewrite a dozen of forms to yaml and that goal basically succeeded. Definitely needs more testing, didn't go live yet.
https://github.com/w010/formhandler

**Comment by luzat** [comment]
I am currently working on another fork at [luzat/formhandler](https://github.com/luzat/formhandler) based on [w010/formhandler](https://github.com/w010/formhandler) to fix additional errors and warnings that I have encountered in a project. Some fixes are:

- Cc works.
- Silencing all deprecations which are not false-positives.
- The `SetLanguage` and `RestoreLanguage` finishers are probably still broken.
- I can display stored submissions from within the backend again.

It works for me so far with `typo3db_legacy` and `modern_template_building`. I see that there have been a couple of commits recently in this repository. How close is this version to being usable and possibly a drop-in replacement for the 2.4-based versions by now @7elix ?

**Comment by w010** [comment]
In the meantime I started to integrate some other fork changes to get rid of typo3db_legacy. Not yet decided if this will be a new fork to replace mine or merged into. Must see which will be better and which one faster. Will decide this week probably, I have this next on my desk because of the project's deadline soon. PS. Current head from my repo went live some time ago on a number of projects and it works ok, but the legacy db must be finally removed

**Comment by 7elix** [comment]
The 10 feature branch https://github.com/PHORAX/formhandler/tree/feature/typo3-version-10-compatibility was merged into master recently.

This version of formhandler does not depend on legacydb since 2019 thanks to https://github.com/PHORAX/formhandler/pull/42

There are still many commits and improvements at e.g. https://github.com/PHORAX/formhandler/pull/62 that need to me ported one commit by one. Feel free to support migrating and feel free to send pull requests for further improvements in other forks.
