### ISSUE TITLE
Page messed up: wrong fluid layout

### ISSUE THREAD

**Issue by klodeckl** [PHORAX/formhandler#7]
The forms are displayed, but the page is messed up: it uses the layout “Default.html“ from typo3/sysext/fluid_styled_content/Resources/Private/Layouts/Default.html instead of my defined layout (page.10.layoutRootPath).

**Comment by 7elix** [comment]
Please send further information since I can not confirm this behaviour generally.

- typoscript setup
- fluid styled content settings

**Comment by 7elix** [comment]
Hi @klodeckl,

this issue will be due to missing feedback.
Feel free to open another issue with the question if the problem remains.

Thanks!

**Comment by klodeckl** [comment]
Problem is solved. The problem was:
Ext fluid_styled_content has a lot of changes, now non-fluid-plugins (like formhandler) use the Generic.html template. In this file <f:layout name="Default" /> is referenced. I had no Default.html layout file in my styles.templates.layoutRootPath setup (was not used in TYPO3 7) and (I don’t know why, maybe a bug) TYPO3 did also not use the Default.html shipped with fluid_styled_content. Instead it used the Default.html layout file defined for my page template. That made the page messed up. Solution: I copied the Default.html layout file shipped with fluid_styled_content to my defined layout path folder. So normally it should be a bug with fluid_styled_content I guess, otherwise it would have used the shipped Default.html layout file.

**Comment by klodeckl** [comment]
I wrote a bug report: https://forge.typo3.org/issues/82338
