### ISSUE TITLE
some trouble after upgrading formhandler

### ISSUE THREAD

**Issue by EnzephaloN** [PHORAX/formhandler#73]
I've upgraded formhandler for using with TYPO3 10.4.
After upgrading I have two major problems:
1. all LLL-marker are empty, which might result [from deprecation and remove](https://docs.typo3.org/c/typo3/cms-core/10.4/en-us/Changelog/9.0/Deprecation-81217-TSFE-relatedLanguageMethods.html)
2. after sending the for I get "Class 'Swift_MimePart' not found", which might result [from deprecation](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88643-RemovedSwiftmailerswiftmailerDependency.html)

Before upgrading formhandler runs fine on TYPO3 9.5.x

Can you help?

**Comment by tan3ot** [comment]
Hi, I've the same error (2.) – I grabbed a copy of the code today. Should this work with TYPO3 10.4 now? Thank you for your work so far!

**Comment by Boa2** [comment]
I get the same  "Class 'Swift_MimePart' not found" error after upgrading to Typo3 10.4.23.
Are you going to replace the swiftmailer dependency with symfony/mailer for this formhandler branch?

**Comment by 7elix** [comment]
https://github.com/PHORAX/formhandler/pull/84
