### ISSUE TITLE
Security Issues: Cross-Site Scripting

### ISSUE THREAD

**Issue by Schweriner** [PHORAX/formhandler#9]
Thanks for the fork. In another fork I saw some upcoming security problems which should be solved in this fork, too: https://github.com/pluspol-interactive/typo3-formhandler/pull/1

**Comment by 7elix** [comment]
Thank you for the notice and link.

Would you please send a Pull-Request this repository in order to ensure future safety.

**Comment by 7elix** [comment]
Hi @Schweriner,

would you please send a pull-request to this repository to fix the security concerns?

Thank you!

**Comment by 7elix** [comment]
> Advisory: https://www.redteam-pentesting.de/advisories/rt-sa-2016-007

**Comment by mgrn0** [comment]
Is this identical with the recently published bulletin here: https://typo3.org/teams/security/security-bulletins/typo3-extensions/typo3-ext-sa-2017-011/ ?

**Comment by Schweriner** [comment]
Pull request has been sent. Sorry for the long delay.
@mgrn0 yes it is.

**Comment by 7elix** [comment]
Thank you, will review PR - and also the version 2.4.1 changes now.

**Comment by hhchrizzo** [comment]
Any updates?
